config/routes.rb
Rails.application.routes.draw do
	root 'emp#home'
	get '/emp/home', :'emp#home'
    # post 'contects/:id', to: 'contects#edit'
    # post 'departments/:id', to: 'departments#edit'
    # post 'projects/:id', to: 'projects#edit'
    # post 'employees/:id', to: 'employees#edit'

	resources :contects, :employees, :projects, :departments
	
	 # controller_name 

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contect.rb
class Contect < ApplicationRecord
end

app/models/department.rb
class Department < ApplicationRecord
	has_many :employees
end

app/models/employee.rb
class Employee < ApplicationRecord
	belongs_to :department, optional:true
	belongs_to :project , optional:true
end

app/models/project.rb
class Project < ApplicationRecord
		has_many :employees
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contects_controller.rb
class ContectsController < ApplicationController
def new 
  	@contects = Contect.new
  end

def index #action
  	@contects = Contect.all
  end

def show
  	@contects = Contect.find_by(id: params[:id])

end

def edit
	  	@contects = Contect.find_by(id: params[:id])

end


# def update
#   if @contects.update(contect_params)
#    flash[:notice] = "Article was updated"
#    redirect_to contect_path(@contects)
#   else
#    flash[:notice] = "Article was not updated"
#    render 'edit'
#   end
# end

def update
	  	@contects = Contect.find_by(id: params[:id])
if @contects.update(emp_params)


  		redirect_to "/contects", :notice=>"your post has been updated"
	else
		#render "new"
		redirect_to "/contects"
	end
end

  
 def create #action
	@contects = Contect.new(emp_params)
	if @contects.save
		redirect_to "/contects"
	else
		render(:new)
	end  	
  end

  def destroy
  	@contects = Contect.find_by(id: params[:id])
  	if @contects.destroy
  		redirect_to "/contects"
	else
		redirect_to "/contects"
	end
  end

  def emp_params
  	params.require(:contect).permit(:name,:email,:mobile, :city, :state)
  end
end


 

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
def new 
  	@departments = Department.new
  end

def index #action
  	@departments = Department.all
  end

def show
      @departments = Department.find_by(id: params[:id])

end
def edit 
      @departments = Department.find_by(id: params[:id])
end

  
 def create #action
	@departments = Department.new(emp_params)
	if @departments.save
		redirect_to "/departments"
	else
		render(:new)
	end  	
  end

  def update
      @departments = Department.find_by(id: params[:id])
if @departments.update(emp_params)


      redirect_to "/departments", :notice=>"your post has been updated"
  else
    #render "new"
    redirect_to "/departments"
  end
end


  def destroy
  	@departments = Department.find_by(id: params[:id])
  	if @departments.destroy
  		redirect_to "/departments"
	else
		redirect_to "/departments"
	end
  end

  def emp_params
  	params.require(:department).permit(:department_name, :department_type,:member_strength,:description)
  end
end

app/controllers/emp_controller.rb
class EmpController < ApplicationController
  def employee
  end

  def project
  end

  def department
  end

  def contact
  end
def create
  @emp23 = Emp.new(emp_params)
  if @emp23.save
   flash[:notice] = "Data was successfully created"
   redirect_to project_path(@emp23)
  else
   render 'project'
  end	

end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index #action

  	@dev = Employee.all
  end

  def create #action
  	@employee = Employee.new(emp_params)
  	if @employee.save
  		redirect_to "/employees"
  	else
  		render(:new)
  	end  	
  end

  def show

    @employees = Employee.find_by(id: params[:id])
  end 

  def edit
   
  @employee = Employee.find_by(id: params[:id])
  end 

  def new
  	@employee = Employee.new
  end

  def update
      @employees = Employee.find_by(id: params[:id])
if @employees.update(emp_params)

redirect_to "/employees", :notice=>"your post has been updated"
  else
    #render "new"
    redirect_to "/employees"
  end
end


  def destroy
  	@employee = Employee.find_by(id: params[:id])
  	if @employee.destroy
  		redirect_to "/employees"
	else
		redirect_to "/employees"
	end
  end

  private

  def emp_params
  	params.require(:employee).permit(:name, :last_name, :age, :department_id, :project_id)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
def new 
  	@projects = Project.new
  end
def index #action
  	@projects = Project.all
  end
def show
    @projects = Project.find_by(id: params[:id])

end

def edit
  @projects = Project.find_by(id: params[:id])
  end 

def update
      @projects = Project.find_by(id: params[:id])
if @projects.update(emp_params)


      redirect_to "/projects", :notice=>"your post has been updated"
  else
    #render "new"
    redirect_to "/projects"
  end
end

  
 def create #action
	@projects = Project.new(emp_params)
	if @projects.save
		redirect_to "/projects"
	else
		render(:new)
	end  	
  end
  def destroy
  	@projects = Project.find_by(id: params[:id])
  	if @projects.destroy
  		redirect_to "/projects"
	else
		redirect_to "/projects"
	end
  end
  def emp_params
  	params.require(:project).permit(:project_name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contects_helper.rb
module ContectsHelper
end

app/helpers/emp_helper.rb
module EmpHelper
end

app/views/contects/edit.html.erb
<h1>Edit Post</h1>
<%=form_for @contects do |f|%>

	<label>Name</label>
	<%=f.text_field :name%>
	<br>
	<label>Email</label>
	<%=f.text_area :email%>
	<br>
	<label>Mobile</label>
	<%=f.text_area :mobile%>
	<br>
	<label>City</label>
	<%=f.text_area :city%>
	<br>
	<label>State</label>
	<%=f.text_area :state%>
	<br>
	
	<%=f.submit "Update Post"%>
<% end -%>

app/views/contects/index.html.erb
<table>
	<thead>
		<th>Name  </th>
		<th>Email </th>
        <th>Mobile  </th>
        <th>City</th>
        <th>State</th>
		
	</thead>
	<tbody>
		<%-@contects.each do |emp|%>
		<tr>
			<td><%=emp.name%></td>
            <td><%=emp.email%></td>
            

            <td><%=emp.mobile%></td>

			<td><%=emp.city%></td>
		    <td><%=emp.state%></td>


			<td><%=link_to "Remove", contect_path(emp), method: :delete %></td>
			<td><%=link_to "Edit", contect_path(emp), method: :edit %></td>
		</tr>
		<%end%>


		
	</tbody>

</table>
<br>
<a href="/contects/new">New Query</a>

app/views/contects/new.html.erb
<%=form_for @contects do |f|%>

	<label>Name</label>
	<%=f.text_field :name%>
	<br>
	<label>Email</label>
	<%=f.text_area :email%>
	<br>
	<label>Mobile</label>
	<%=f.text_area :mobile%>
	<br>
	<label>City</label>
	<%=f.text_area :city%>
	<br>
	<label>State</label>
	<%=f.text_area :state%>
	<br>
	
	<%=f.submit "Submit"%>
<% end -%>

app/views/departments/edit.html.erb
<%=form_for @departments do |f|%>

	<label>Department Name</label>
	<%=f.text_field :department_name%>
	<br>
	<label>Department Type</label>
	<%= f.select :department_type, ['Sales', 'Marketing', 'Financial','IT','Logistics','Production','Security'], prompt:"select"%>

	<br><br>
    <label>Member Strength</label>
	<%=f.text_field :member_strength%>
	<br>

	<label>Description</label>
	<%=f.text_area :description%>
	<br>	
	
	<%=f.submit "Create Department"%>
<% end -%>

app/views/departments/index.html.erb
<table>
	<thead>
		<th>Department Name  </th>
		<th>Department Type  </th>
        <th>Member Strength  </th>
        <th>Description  </th>

		
	</thead>
	<tbody>
		<%-@departments.each do |emp|%>
		<tr>
			<td><%=emp.department_name%></td>
            <td><%=emp.department_type%></td>


            <td><%=emp.member_strength%></td>

			<td><%=emp.description%></td>
			
			<td><%=link_to "Remove", department_path(emp), method: :delete %>
				</td>

			<td><%=link_to "Edit", department_path(emp), method: :edit %>
			</td>

		</tr>

		<%end%>
 	

		
	</tbody>

</table>
<br>
<a href="/departments/new">Create Department</a>

app/views/departments/new.html.erb
<%=form_for @departments do |f|%>

	<label>Department Name</label>
	<%=f.text_field :department_name%>
	<br>
	<label>Department Type</label>
	<%= f.select :department_type, ['Sales', 'Marketing', 'Financial','IT','Logistics','Production','Security'], prompt:"Select"%>

	<br><br>
    <label>Member Strength</label>
	<%=f.text_field :member_strength%>
	<br>

	<label>Description</label>
	<%=f.text_area :description%>
	<br>	
	
	<%=f.submit "Create Department"%>
<% end -%>

app/views/emp/contact.html.erb
<h1>Contact File </h1>

app/views/emp/create.html.erb
<h1>Create an Article</h1>
<%= form_for @emp23 do |f| %>
 <p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
 </p>
 <p>
  <%= f.label :description %><br>
  <%= f.text_area :description %>
 </p>
 <p>
  <%= f.submit %>
 </p>
<% end %>


<!--<%# if @emp23.errors.any? %>
 <h2>The following errors prevented the article from saving:</h2>
 <ul>
 <%# @emp23.errors.full_messages.each do |msg|%>
 <li><%= msg %></li>
 <%# end %>
 </ul>
<%# end %>
<%#= link_to 'Back', project_path %>

app/views/emp/department.html.erb
<h1>Emp#department</h1>
<p>Find me in app/views/emp/department.html.erb</p>

app/views/emp/employee.html.erb
<h1>Emp#employee</h1>
<p>Find me in app/views/emp/employee.html.erb</p>

app/views/emp/home.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Text Animation</title>
    
 
   
</head>
<body onload="init();">
    <div class="banner">
    <div class="subdiv">
<h1><marquee direction="right" >Welcome to Employee Management System</marquee></h1>
    </div>
</div>
</body>
</html>

app/views/emp/project.html.erb
<h1>This is the Project Page of the Employee</h1>

app/views/employees/edit.html.erb
<%=form_for @employee do |f|%>
	<label>name</label>
	<%=f.text_field :name%>
	<br>
	<label>last name</label>
	<%=f.text_field :last_name%>
	<br>
	<label>Age</label>
	<%=f.text_field :age%>
	<br>
	<label>Department</label>
	<%=f.select :department_id, Department.all.pluck(:department_name, :id)%>
	<br>
	<%=f.submit "Create Employee"%>
<% end -%>

app/views/employees/index.html.erb
<table>
	<thead>
		<th>First Name</th>
		<th>Last Name</th>
		<th>Age</th>
		<th>Department</th>
		<th>Project Name</th>
	</thead>
	<tbody>
		<%-@dev.each do |emp|%>
		<tr>
			<td><%=emp.name%></td>
			<td><%=emp.last_name%></td>
			<td><%=emp.age%></td>
			<td><%=emp.department.try(:department_name) %></td>
            <td><%=emp.project.try(:project_name) %></td>
			<td><%=link_to "Delete", employee_path(emp), method: :delete %></td>
			<td><%=link_to "Edit", edit_employee_path(emp) %></td>

		</tr>
		<%end%>
		
	</tbody>
</table>
<a href="/employees/new", style="color: #FF33F9 ">Create Employee</a>

app/views/employees/new.html.erb
<%=form_for @employee do |f|%>
	<label>First Name</label>
	<%=f.text_field :name%>
	<br>
	<label>Last Name</label>
	<%=f.text_field :last_name%>
	<br>
	<label>Age</label>
	<%=f.text_field :age%>
	<br>
	<label>Department Name</label>
	<%=f.select :department_id, Department.all.pluck(:department_name, :id)%>
	<br>
	<label>Project Name</label>
	<%=f.select :project_id, Project.all.pluck(:project_name, :id)%>
	<br>
	<%=f.submit "Create Employee"%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Employeee</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header">
      <h1>Welcome to Employee Management System</h1>
      <p>Always Ahead</p>
    </div>

    <div class="vertical-menu">
      <a href ="/emp/home">Home</a>
      <a href="/employees">Employee</a>
      <a href="/projects">Project</a>
      <a href="/departments">Department</a>
      <a href="/contects">Contact Us</a>
    </div>

    <div class="main_content">
      <%= yield %>
    </div>
  </body>

</html>

app/views/projects/create.html.erb
<h1>Create</h1>
<%= form_for @projects do |f| %>
 <p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
 </p>
 <p>
  <%= f.label :description%><br>
  <%= f.text_area :description %>
 </p>
 <p>
  <%= f.submit ,style="color: green"%>
 </p>
<% end %>

app/views/projects/edit.html.erb
<%=form_for @projects do |f|%>

	<label>Project Name</label>
	<%=f.text_field :project_name%>
	<br>
	<label>Description</label>
	<%=f.text_area :description%>
	<br>
	
	<%=f.submit "Create Project"%>
<% end -%>

app/views/projects/index.html.erb
<table>
	<thead>
		<th>Project Name</th>
		<th>Description</th>
		
	</thead>
	<tbody>
		<%-@projects.each do |emp|%>
		<tr>
			<td><%=emp.project_name%></td>
			<td><%=emp.description%></td>
			
			<td><%=link_to "Remove", project_path(emp), method: :delete %></td>
			<td><%=link_to "Edit", edit_project_path(emp) %></td>
			<td><%=link_to "Show", project_path(emp) %></td>
		</tr>
		<%end%>
		
	</tbody>
</table>
<a href="/projects/new", style="color: #FF3377">Create Project</a>

app/views/projects/new.html.erb
<%=form_for @projects do |f|%>

	<label>Project Name</label>
	<%=f.text_field :project_name%>
	<br>
	<label>Description</label>
	<%=f.text_area :description%>
	<br>
	
	<%=f.submit "Create Project"%>
<% end -%>

app/views/projects/show.html.erb
<table>
	<thead>
		<th>Project Name</th>
	    <th>Employee Name</th>
	</thead>
	<tbody>
	<td><%=@projects.project_name%></td>	
    
    <%-@projects.employees.each do |emp|%>
		
			<td><%=emp.name%></td>


		<%end%>	
</tbody>

	</table>